fixing pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -73,6 +73,13 @@ jobs:
       - name: Verify JAR exists
         run: ls -la target
 
+      - name: Validate Docker credentials
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "❌ Missing DOCKERHUB_USERNAME"; exit 1; fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "❌ Missing DOCKERHUB_TOKEN"; exit 1; fi
+
       - name: Login Docker Hub
         uses: docker/login-action@v3
         with:
